framework:
    messenger:
        transports:
            async:
                dsn: 'doctrine://default?auto_setup=true'
                options:
                    use_notify: true
                    check_delayed_interval: 60000

        routing:
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': async
