controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Logout route (gérée par security firewall)
app_logout:
    path: /logout
    methods: GET